# Generated by Django 5.2.1 on 2025-05-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicelineapproval",
            options={
                "permissions": [
                    ("approve_invoiceline", "Can approve/deny/query invoice lines")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="issuancerequest",
            options={
                "permissions": [
                    ("submit_issuance", "Can submit and view issuance requests"),
                    ("approve_issuance", "Can approve/deny/query internal issuance"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="lowstockalert",
            options={
                "permissions": [
                    ("acknowledge_lowstock", "Can acknowledge low-stock alerts")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "permissions": [("process_payment", "Can create and finalize payments")]
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "permissions": [
                    ("create_purchaseorder", "Can view and generate PO drafts"),
                    ("approve_purchaseorder", "Can approve/deny/query POs"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="receiving",
            options={
                "permissions": [
                    ("record_receiving", "Can record goods receipt and upload invoice")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="requisition",
            options={
                "permissions": [
                    ("submit_requisition", "Can submit and view requisitions"),
                    ("approve_requisition", "Can approve/deny/query requisitions"),
                ]
            },
        ),
    ]
