# Generated by Django 5.2.2 on 2025-06-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0003_requisition_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("SUPPLIER", "Supplier"), ("STORE", "Store")],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('supplychain', 'Destination').objects.bulk_create([
                apps.get_model('supplychain', 'Destination')(name='SUPPLIER'),
                apps.get_model('supplychain', 'Destination')(name='STORE'),
            ])
        ),
        migrations.AddField(
            model_name="issuancerequest",
            name="requisition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issuance_request",
                to="supplychain.requisition",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.destination",
            ),
        ),
    ]
