# Generated by Django 5.2.3 on 2025-06-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0004_destination_issuancerequest_requisition_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requisition",
            options={
                "permissions": [
                    ("submit_requisition", "Can submit and view requisitions"),
                    ("approve_requisition", "Can approve/deny/query requisitions"),
                    ("view_all_requisitions", "Can view all requisitions"),
                ]
            },
        ),
    ]
