# Generated by Django 5.2.2 on 2025-06-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0004_destination_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.destination",
            ),
        ),
    ]
