# Generated by Django 5.2.3 on 2025-06-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0005_alter_requisition_options"),
        ("supplychain", "0006_alter_requisition_options"),
    ]

    operations = []
