# Generated by Django 5.2.3 on 2025-06-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0007_merge_20250614_1744"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase Requisition"),
                            ("STORE", "Store Requisition"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="destination",
        ),
        migrations.AddField(
            model_name="requisition",
            name="purchase_category",
            field=models.CharField(
                blank=True,
                choices=[("CONSUMABLE", "Consumables"), ("SERVICE", "Services")],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="requisition_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.requisitiontype",
            ),
        ),
        migrations.DeleteModel(
            name="Destination",
        ),
    ]
