# Generated by Django 5.2.3 on 2025-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0007_merge_20250614_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitionapproval",
            name="snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
