# Generated by Django 5.2.3 on 2025-08-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0007_merge_20250614_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.destination",
                verbose_name="Requisition Type",
            ),
        ),
    ]
