# Generated by Django 5.2.3 on 2025-08-23 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0008_alter_requisition_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier_destination_sub_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CONSUMABLES", "CONSUMABLES"),
                            ("SERVICES", "Services"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="requisition",
            name="Supplier_destination_sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.supplier_destination_sub_category",
                verbose_name="Supplier Sub-Category",
            ),
        ),
    ]
