# Generated by Django 5.2.3 on 2025-08-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0009_supplier_destination_sub_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="Supplier_destination_sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.supplier_destination_sub_category",
                verbose_name="Supplier Sub-Category",
            ),
        ),
    ]
