# Generated by Django 5.2.3 on 2025-08-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0010_alter_requisition_supplier_destination_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="Supplier_destination_sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.supplier_destination_sub_category",
                verbose_name="Supplier Sub-Category",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.destination",
            ),
        ),
    ]
