# Generated by Django 5.2.3 on 2025-09-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplychain",
            "0011_alter_requisition_supplier_destination_sub_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitionitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="supplychain.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="supplier_destination_sub_category",
            name="name",
            field=models.CharField(
                choices=[("CONSUMABLES", "CONSUMABLES"), ("SERVICES", "SERVICES")],
                max_length=20,
                unique=True,
            ),
        ),
    ]
