# Generated by Django 5.2.3 on 2025-10-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0013_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
