# Generated by Django 5.2.3 on 2025-11-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0017_add_supplier_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(
                choices=[("PURCHASE", "Purchase"), ("STORE", "Store")],
                max_length=10,
                unique=True,
            ),
        ),
    ]
