# Generated by Django 5.2.3 on 2025-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0019_normalize_destination_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(
                choices=[("PURCHASE", "PURCHASE"), ("STORE", "STORE")],
                max_length=10,
                unique=True,
            ),
        ),
    ]
