# Generated by Django 5.2.3 on 2025-11-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0021_alter_supplier_destination_sub_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier_destination_sub_category",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("CONSUMABLES", "CONSUMABLES"), ("SERVICES", "SERVICES")],
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
