# Generated by Django 5.2.3 on 2025-11-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0022_alter_supplier_destination_sub_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="Supplier_destination_sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.supplier_destination_sub_category",
                verbose_name="Supplier Sub-Category",
            ),
        ),
    ]
