# Generated by Django 5.2.3 on 2025-11-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0023_alter_requisition_supplier_destination_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_COO", "Pending COO Approval"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("QUERIED", "Queried"),
                    ("SENT", "Sent to Supplier"),
                    ("PROCURED", "Procured"),
                ],
                default="PENDING_COO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderapproval",
            name="action",
            field=models.CharField(
                choices=[
                    ("PENDING_COO", "Pending COO Approval"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("QUERIED", "Queried"),
                    ("SENT", "Sent to Supplier"),
                    ("PROCURED", "Procured"),
                ],
                max_length=20,
            ),
        ),
    ]
