# Generated by Django 5.2.3 on 2025-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0024_alter_purchaseorder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_COO", "Pending COO Approval"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("QUERIED", "Queried"),
                ],
                default="PENDING_COO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderapproval",
            name="action",
            field=models.CharField(
                choices=[
                    ("PENDING_COO", "Pending COO Approval"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("QUERIED", "Queried"),
                ],
                max_length=20,
            ),
        ),
    ]
