# Generated by Django 5.2.3 on 2025-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0025_alter_purchaseorder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="supplier_invoice",
            field=models.FileField(
                blank=True, null=True, upload_to="supplier_invoices/"
            ),
        ),
    ]
