# Generated by Django 5.2.3 on 2025-12-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0026_alter_receiving_received_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receiving",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Receipt"),
                    ("UNDER_REVIEW", "Pending Accounting Review"),
                    ("APPROVED", "Approved"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when goods were actually received.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who physically recorded the receipt of goods.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="supplier_invoice",
            field=models.FileField(
                blank=True,
                help_text="Supplier invoice document for this receipt (optional).",
                null=True,
                upload_to="supplier_invoices/",
            ),
        ),
    ]
