# Generated by Django 5.2.3 on 2025-12-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0027_receiving_status_alter_receiving_received_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Receipt"),
                    ("UNDER_REVIEW", "Pending Accounting Review"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
