# Generated by Django 5.2.3 on 2025-12-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0028_alter_receiving_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="supplier_invoice",
            field=models.FileField(
                help_text="Supplier invoice document for this receipt (optional).",
                null=True,
                upload_to="supplier_invoices/",
            ),
        ),
    ]
