# Generated by Django 5.2.3 on 2025-12-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0029_alter_receiving_supplier_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisitionitem",
            name="supplier",
        ),
        migrations.AddField(
            model_name="requisition",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisitions",
                to="supplychain.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Receipt"),
                    ("UNDER_REVIEW", "Pending Accounting Review"),
                    ("REVIEWED", "Reviewed and Cleared for Payment"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="requisitionitem",
            constraint=models.UniqueConstraint(
                fields=("requisition", "product"), name="uniq_requisition_product"
            ),
        ),
    ]
