# Generated by Django 5.2.3 on 2025-12-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplychain",
            "0030_remove_requisitionitem_supplier_requisition_supplier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="purchase_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivings",
                to="supplychain.purchaseorder",
            ),
        ),
    ]
