# Generated by Django 5.2.3 on 2025-12-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0031_alter_receiving_purchase_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivings",
                to="supplychain.purchaseorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="receiving",
            constraint=models.UniqueConstraint(
                fields=("purchase_order",), name="unique_receiving_per_purchase_order"
            ),
        ),
    ]
