# Generated by Django 5.2.3 on 2025-12-14 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0032_alter_receiving_purchase_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiving",
            options={
                "permissions": [
                    ("record_receiving", "Can record goods receipt and upload invoice"),
                    ("review_receiving", "Can perform accounting review on receivings"),
                    (
                        "amend_receiving",
                        "Can amend receivings after accounting query (COO)",
                    ),
                ]
            },
        ),
        migrations.AddField(
            model_name="receiving",
            name="amended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when COO amended this receiving after query.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="amended_by",
            field=models.ForeignKey(
                blank=True,
                help_text="COO who amended the receiving after query.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_amended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="amendment_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional COO notes for amendments made after query.",
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="review_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional accounting notes for the overall receiving.",
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when accounting completed review (cleared or queried).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Accountant who cleared/queried this receiving.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receivingitem",
            name="accounting_notes",
            field=models.TextField(
                blank=True, help_text="Accounting notes for why this line was queried."
            ),
        ),
        migrations.AddField(
            model_name="receivingitem",
            name="accounting_queried",
            field=models.BooleanField(
                default=False,
                help_text="Accounting marked this line as queried/incorrect.",
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Receipt"),
                    ("UNDER_REVIEW", "Pending Accounting Review"),
                    ("QUERIED", "Queried (Needs COO Amendment)"),
                    ("REVIEWED", "Reviewed and Cleared for Payment"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="supplier_invoice",
            field=models.FileField(
                blank=True,
                help_text="Supplier invoice document for this receipt (optional).",
                null=True,
                upload_to="supplier_invoices/",
            ),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="actual_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
