# Generated by Django 5.2.3 on 2025-12-14 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0033_alter_receiving_options_receiving_amended_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="amended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="amended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_amended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="amendment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="accounting_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="accounting_queried",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="flagged_for",
            field=models.JSONField(default=dict),
        ),
    ]
