# Generated by Django 5.2.3 on 2025-12-14 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0034_alter_receiving_amended_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiving",
            name="amended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when COO amended this receiving after query.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="amended_by",
            field=models.ForeignKey(
                blank=True,
                help_text="COO who amended the receiving after accounting query.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_amended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="amendment_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional COO notes describing what was amended after query.",
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when goods were actually received.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who physically recorded the receipt of goods.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="review_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional accounting notes for the overall receiving (summary/exceptions).",
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when accounting completed review (cleared or queried).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Accountant who cleared/queried this receiving.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="accounting_notes",
            field=models.TextField(
                blank=True,
                help_text="Accounting notes explaining why this line was queried.",
            ),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="accounting_queried",
            field=models.BooleanField(
                default=False,
                help_text="Accounting marked this line as queried/incorrect.",
            ),
        ),
        migrations.AlterField(
            model_name="receivingitem",
            name="flagged_for",
            field=models.JSONField(
                default=dict,
                help_text="Keys: kitchen, store, audit, admin; values: booleans",
            ),
        ),
    ]
