# Generated by Django 5.2.3 on 2025-12-14 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0035_alter_receiving_amended_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiving",
            options={
                "permissions": [
                    ("record_receiving", "Can record goods receipt and upload invoice"),
                    ("review_receiving", "Can perform accounting review on receivings"),
                    ("approve_receiving", "Can approve/deny receivings (COO)"),
                    ("amend_receiving", "Legacy (do not use)"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="receiving",
            name="amended_at",
        ),
        migrations.RemoveField(
            model_name="receiving",
            name="amended_by",
        ),
        migrations.RemoveField(
            model_name="receiving",
            name="amendment_notes",
        ),
        migrations.AddField(
            model_name="receiving",
            name="coo_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receiving",
            name="coo_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_coo_decided",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receiving",
            name="coo_decision_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receiving",
            name="sent_to_coo_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receiving",
            name="sent_to_coo_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivings_sent_to_coo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receiving",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Receipt"),
                    ("UNDER_REVIEW", "Pending Accounting Review"),
                    ("PENDING_COO", "Pending COO Approval"),
                    ("REVIEWED", "Cleared for Payment"),
                    ("DENIED", "Denied"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
