# Generated by Django 5.2.3 on 2025-12-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplychain",
            "0036_alter_receiving_options_remove_receiving_amended_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuancerequest",
            name="requester",
        ),
        migrations.RemoveField(
            model_name="issuancerequest",
            name="requisition",
        ),
        migrations.DeleteModel(
            name="IssuanceItem",
        ),
        migrations.DeleteModel(
            name="IssuanceRequest",
        ),
    ]
