# Generated by Django 5.2.3 on 2025-12-16 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0038_payment_created_by_payment_processed_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="approved_by_mum",
            new_name="approved_by_coo",
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_last4",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="payment",
            name="cheque_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="payment",
            name="transfer_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_proof",
            field=models.FileField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHEQUE", "Cheque"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CASH", "Cash"),
                    ("CARD", "Card Payment"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("purchase_order",), name="unique_payment_per_purchase_order"
            ),
        ),
    ]
