# Generated by Django 5.2.3 on 2025-12-16 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0039_rename_approved_by_mum_payment_approved_by_coo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="source_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("REQUISITION", "Requisition"),
                    ("RECEIVING", "Receiving"),
                    ("STOCKTAKE", "Stocktake"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("RECEIVE", "Receive"),
                    ("ISSUE", "Issue"),
                    ("ADJUST", "Adjust"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.UniqueConstraint(
                fields=("transaction_type", "source_type", "source_id", "product"),
                name="uniq_stocktxn_per_source_product",
            ),
        ),
    ]
