# Generated by Django 5.2.3 on 2025-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0040_remove_stocktransaction_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=64, null=True, blank=True)
        ),
    ]
