# Generated by Django 5.2.3 on 2025-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0042_backfill_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
