# Generated by Django 5.2.3 on 2025-12-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0043_alter_product_sku"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("bulk_upload_products", "Can bulk upload products")]
            },
        ),
    ]
