# Generated by Django 5.2.3 on 2025-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0044_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
