# Generated by Django 5.2.3 on 2025-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0046_lowstockalert_acknowledged_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("REQUISITION", "Requisition"),
                    ("RECEIVING", "Receiving"),
                    ("STOCKTAKE", "Stocktake"),
                    ("BULK_UPLOAD", "Bulk Upload"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("RECEIVE", "Receive"),
                    ("ISSUE", "Issue"),
                    ("ADJUST_IN", "Adjust In"),
                    ("ADJUST_OUT", "Adjust Out"),
                ],
                max_length=10,
            ),
        ),
    ]
