# Generated by Django 5.2.3 on 2025-12-17 14:06

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0047_alter_stocktransaction_source_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("uom"),
                name="uniq_product_sku",
            ),
        ),
    ]
