# Generated by Django 5.2.3 on 2025-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0048_product_uniq_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="evidence",
            field=models.FileField(upload_to="requisition_evidence/"),
        ),
    ]
