# Generated by Django 5.2.13 on 2026-05-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0052_organisation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplychain.organisation'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplychain.organisation'),
        ),
    ]
